#!/usr/bin/env python3

import json
import re
import sys

PRODUCT_CONFIG_FILE_PATH: str = "/usr/lib/code/product.json"

STORE_NAME_VISUALSTUDIOCOM: str = "visualstudio"
STORE_NAME_OPENVSX: str         = "openvsx"

CONFIG_STORE_OPENVSX: dict = dict([
    ('serviceUrl',  "https://open-vsx.org/vscode/gallery"),
    ('itemUrl',     "https://open-vsx.org/vscode/item"),
    ('cacheUrl',    False),
    ('storeName',   'open-vsx.org')
])

CONFIG_STORE_VISUALSTUDIOCOM: dict = dict([
    ('serviceUrl',  "https://marketplace.visualstudio.com/_apis/public/gallery"),
    ('itemUrl',     "https://marketplace.visualstudio.com/items"),
    ('cacheUrl',    "https://vscode.blob.core.windows.net/gallery/index"),
    ('storeName',   'marketplace.visualstudio.com')
])

opts = [opt for opt in sys.argv[1:] if opt.startswith("-")]
args = [arg for arg in sys.argv[1:] if not arg.startswith("-")]

def readDeserializedProductConfig():
    with open(PRODUCT_CONFIG_FILE_PATH, 'r') as product_config_file_open:
        product_config_deserialized = json.load(product_config_file_open)
        return product_config_deserialized

def writeSerializedProductConfig(json_data_serialized_to_write):
    with open(PRODUCT_CONFIG_FILE_PATH, 'w') as product_config_file_write:
        json.dump(
            json_data_serialized_to_write,
            product_config_file_write,
            indent="\t"
        )

def returnDomaineNameFromURL(urlToRegex: str) -> str:
    match = re.search('https?://([A-Za-z_0-9.-]+).*', urlToRegex)
    if match:
        return match.group(1)
    else:
        return False

def getStoreName(jsonSerializeConfig) -> str:
    return returnDomaineNameFromURL(getServiceUrl(jsonSerializeConfig))

def getServiceUrl(jsonSerializeConfig) -> str:
    return jsonSerializeConfig["extensionsGallery"]["serviceUrl"]

def setServiceUrl(jsonSerializeConfig, value):
    jsonSerializeConfig["extensionsGallery"]["serviceUrl"] = value
    return jsonSerializeConfig

def getItemUrl(jsonSerializeConfig) -> str:
    return jsonSerializeConfig["extensionsGallery"]["itemUrl"]

def setItemUrl(jsonSerializeConfig, value):
    jsonSerializeConfig["extensionsGallery"]["itemUrl"] = value
    return jsonSerializeConfig

def getCacheUrl(jsonSerializeConfig):
    if ("cacheUrl" in jsonSerializeConfig["extensionsGallery"]):
        return jsonSerializeConfig["extensionsGallery"]["cacheUrl"]
    else:
        return False

def setCacheUrl(jsonSerializeConfig, value):
    if (value):
        jsonSerializeConfig["extensionsGallery"]["cacheUrl"] = value
    else:
        del jsonSerializeConfig["extensionsGallery"]["cacheUrl"]
    return jsonSerializeConfig



def getStoreConfig() -> dict:
    product_config_json_deserialized = readDeserializedProductConfig()

    return_config = dict([
        ("serviceUrl", False),
        ("itemUrl", False),
        ("cacheUrl", False),
        ("storeName", False)
    ])

    return_config['serviceUrl'] = getServiceUrl(product_config_json_deserialized)
    return_config['itemUrl']    = getItemUrl(product_config_json_deserialized)
    return_config['cacheUrl']   = getCacheUrl(product_config_json_deserialized)
    return_config['storeName']  = getStoreName(product_config_json_deserialized)

    return return_config

def setStoreConfig(service_url: str, item_url: str, cache_url):
    product_config_json_deserialized = readDeserializedProductConfig()

    setServiceUrl(product_config_json_deserialized, service_url)
    setItemUrl(product_config_json_deserialized, item_url)
    setCacheUrl(product_config_json_deserialized, cache_url)

    writeSerializedProductConfig(product_config_json_deserialized)

def printStoreConfig(isDiplayAllInformations: bool = False):
    config_to_show = getStoreConfig()

    print(
        "Current store is configure for {storeName}"
        .format(
            storeName = config_to_show['storeName']
        )
    )

    if (isDiplayAllInformations):
        if (not config_to_show['cacheUrl']):
            config_to_show['cacheUrl'] = "empty"

        print(
"""serviceUrl: {serviceUrl}
itemUrl:    {itemUrl}
cacheUrl:   {cacheUrl}"""
            .format(
                serviceUrl = config_to_show['serviceUrl'],
                itemUrl = config_to_show['itemUrl'],
                cacheUrl = config_to_show['cacheUrl']
            )
        )

def printSuccessfulStoreDefine():
    config_to_show = getStoreConfig()

    print(
        "The store is now for {storeName}"
        .format(
            storeName = config_to_show['storeName']
        )
    )

def setStoreVisualStudioCom():
    setStoreConfig(
        CONFIG_STORE_VISUALSTUDIOCOM['serviceUrl'],
        CONFIG_STORE_VISUALSTUDIOCOM['itemUrl'],
        CONFIG_STORE_VISUALSTUDIOCOM['cacheUrl']
    )

def setStoreOpenVSX():
    setStoreConfig(
        CONFIG_STORE_OPENVSX['serviceUrl'],
        CONFIG_STORE_OPENVSX['itemUrl'],
        CONFIG_STORE_OPENVSX['cacheUrl']
    )



if __name__ == "__main__":

    if "-h" in opts or "--help" in opts:
        print(
"""vscode_store - configure extension registry for Visual Studio Code.

DESCRIPTION

You can use several options :

    -l, --list  Show actual store use

    -s, --set store_name
                Change store to store_name.
                You can replace it with "visualstudio" for use official Microsoft extension store, or "openvsx" for use Open VSX registry."""
        )

    if "-l" in opts or "--list" in opts:
        printStoreConfig()

    if "-la" in opts or "--list-all" in opts:
        printStoreConfig(True)
    
    if "-s" in opts or "--set" in opts:
        if (args[0] == STORE_NAME_VISUALSTUDIOCOM):
            setStoreVisualStudioCom()
            printSuccessfulStoreDefine()
        elif (args[0] == STORE_NAME_OPENVSX):
            setStoreOpenVSX()
            printSuccessfulStoreDefine()
